export const copy = {
  home: {
    title: "Ramazan'da küçük bir iyilik",
    subtitleLine1: "Bugün bir kalp için güzel bir niyet.",
    subtitleLine2: "Sessizce. Sakinlikle.",
    ctaDua: "Bu Akşam Bir Dua",
    ctaAbout: "Minik Not",
    footer: "Bu sayfa, içi ısıtsın diye yapıldı.",
  },
  dua: {
    kicker: "Niyet akışı",
    title: "Kısa Niyet",
    subtitle: "Üç küçük adım.",
    next: "Devam et",
    back: "Geri",
    finish: "Tamamla",
    restart: "Bir niyet daha",
    share: "Paylaş",
    copied: "Kopyalandı",
    shareError: "Paylaşım şu an açılamadı",
    step1: {
      prompt: "Kimin için?",
      options: ["Ailem", "Bir dost", "Kendim", "İsmini söylemeden biri"],
    },
    step2: {
      prompt: "Niyet",
      options: ["Huzur", "Ferahlık", "Kolaylık", "Cesaret"],
    },
    step3: {
      prompt: "Kısa dua / niyet cümlesi",
    },
    templates: [
      "Bu gece ailene huzur dolsun.",
      "Ailenin evi sakinlikle aydınlansın.",
      "Bir dosta ferahlık gelsin.",
      "Dostunun içi genişlesin, kalbi hafiflesin.",
      "Kendine kolaylık nasip olsun.",
      "Adımların kolaylaşsın, yükün azalsın.",
      "İsmini bilmediğin birine cesaret doğsun.",
      "O kalbe bugün güç ve sabır gelsin.",
      "Bu gece kapına huzurlu bir nefes değsin.",
      "Kalbin ferah, yolun açık olsun.",
      "Bugün zor olan, yarın daha kolay olsun.",
      "Karanlık azalsın, içindeki ışık çoğalsın.",
    ],
    finalNote: "Bu niyet Ramazan için seçildi.\nVe evet, biri biraz uğraştı.",
  },
  about: {
    kicker: "Gentle note",
    title: "About This Space",
    line1: "This is a small Ramadan corner.",
    line2: "It is quiet, warm, and simple by design.",
    line3: "Use it for a short pause before prayer or rest.",
    backHome: "Back to Home",
  },
};
